[workspace]
members = [
    "test-d1-flash-bt0",
    "xtask"
]
default-members = ["xtask"]

# Leave debug symbol information on release compilation mode
# That's okay, these symbols won't appear on flash binary
[profile.release]
debug = true
